// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4LD2xKdgZ6zAevwZZwHk6m_vp2wly0YU',
    appId: '1:840377313660:android:4d237ed9b998cd9bd39cf9',
    messagingSenderId: '840377313660',
    projectId: 'covidapp-98f7c',
    storageBucket: 'covidapp-98f7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbQx8WXEpRXDwslXE2bXNoc90SXAWf99c',
    appId: '1:840377313660:ios:ded128523ea8ababd39cf9',
    messagingSenderId: '840377313660',
    projectId: 'covidapp-98f7c',
    storageBucket: 'covidapp-98f7c.appspot.com',
    iosClientId: '840377313660-4ia6e3658t86lq6dli20njm77fum65si.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
